RECIPE_ADDED_MSG = 'Рецепт уже добавлен.'
NO_RECIPE_MSG = 'Рецепта нет'
RECIPE_DELETE_MSG = 'Рецепт удален'
YOUSELF_SUBSCRIBE_MSG = 'Нельзя подписаться на самого себя!'
NO_UNIQUE_SUBSCRIBE_MSG = 'Вы уже подписаны на этого автора!'
YOUSELF_SUBSCRIBE_DEL_MSG = 'Нельзя отписаться от самого себя!'
NO_SUBSCIBE_MSG = 'Вы не подписаны на этого автора!'
MIN_COOKING_TIME = 1
MIN_VALUE_MSG = 'Время приготовления меньше 1'
TYPE_ERROR_MSG = 'Введенное значение не является числом.'
MIN_INGR_MSG = 1
NO_UNIQUE_TAG_MSG = 'Такой тег уже использован.'
MIN_INGR_ERR_MSG = 'Количество ингредиента должно быть больше 0.'
NO_UNIQUE_INGR_MSG = 'Такой ингредиент уже добавлен.'
NO_UNIQUE_EMAIL_MSG = 'Такая электронная почта уже используется.'
ERROR_NAME_MSG = 'Нельзя использовать такое имя.'
NO_UNIQUE_NAME_MSG = 'Пользователь с таким именеи уже существует.'
MIN_COOK_TIME_VALUE = 1
MAX_COOK_TIME_VALUE = 480
MIN_COOK_TIME_VALUE_MSG = 'Значение должно быть не меньше "1".'
MAX_COOK_TIME_VALUE_MSG = 'Готовить 8 часов? Такой рецепт тут не нужен!'
STR_LENGHT = 15