# Generated by Django 3.2.16 on 2023-01-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Веберите тэги.', related_name='recipes', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
