# Generated by Django 3.2.16 on 2023-01-06 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20230105_2055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='add_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='add_shopping_list',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipe_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipe_shopping_list'),
        ),
    ]
