# Generated by Django 3.2.16 on 2023-01-10 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления блюда в минутах', validators=[django.core.validators.MinValueValidator(1, message='Значение должно быть не меньше "1".'), django.core.validators.MaxValueValidator(480, message='Готовить 8 часов? Такой рецепт тут не нужен!')], verbose_name='Время приготовления (минут)'),
        ),
    ]
